import NavBar from "@/components/navbar";
import localFont from "next/font/local";
import "./globals.css";

const fraunces = localFont({ src: "./fonts/Fraunces--latin_basic.woff2" });

export const metadata = {
  title: "selinand's halloween",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`bg-background ${fraunces.className} font-thin text-2xl`}
        style={{ fontVariationSettings: `"WONK" 1` }}
      >
        <NavBar />
        <div className="h-[calc(100vh-74px)] mt-[74px]">{children}</div>
      </body>
    </html>
  );
}
