import NavBar from "@/components/navbar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-background">
        <NavBar />
        <div className="h-[calc(100vh-74px)]">{children}</div>
      </body>
    </html>
  );
}
