const costume_ideas = [
  "kamala harris + coconut",
  "donald trump + biden",
  "brat + charli xcx",
  "ai charlie & the chocolate factory",
  "smoking duck",
  "sabrina carpenter + espresso",
  "orlando baby + four seasons",
  "ariana grande + spongebob",
  "spongebob + patrick",
  "(group) → taylor swift eras",
  "chapell roan + pink pony",
  "donald trump getting shot",
  "taylor and a red scarf",
  "cowboy carter",
  "bruno mars and las vegas",
  "bruno mars and lady gaga",
  "harley quinn and joker lady gaga version",
  "iphone and hot chip",
  "deadpool and wolverine",
  "jojo siwa",
  "nikocado avocado",
  "challengers",
  "inside out 2",
  "the bear",
  "reality tv shows",
  "wednesday",
  "scott pilgrim",
  "taylor swift and travis kelce",
  "ice spice and pinkpantheress",
  "mr. beast and youtube",
  "pride flags",
  "pup + master",
  "lana del rey and waffle house",
  "jojo siwa",
  "kate middleton and cancer",
  "barbie and ken",
  "kendrick and drake",
  "drake and millie",
  "glinda and elphaba (wicked)",
  "saltbrun",
  "avatar ",
  "percy jackson ",
  "kyle + rock wall",
  "ethan + peanut",
  "clara + sonic",
  "seasons",
  "nicole + boat",
  "tree + fire (forest fire)",
  "alberta + water",
  "hatsune miku",
  "beauty and the beast",
  "dress up as one of ur friends/ each other",
  "your fav childhood show",
  "powerpuff girls",
  "totally spies",
  "fairly odd parents",
  "adventure time",
  "fav albums",
  "fav meme",
  "trad wife content creator (nara smith, lucky blue, etc)",
  "hawk tuah",
  "beetlejuice ",
  "australian olympic breakdancer",
  "river (la seine) and poop",
  "hotel translvania",
];

export async function fetchIdea() {
  return costume_ideas[Math.floor(Math.random() * costume_ideas.length)];
}
